### ISSUE TITLE
review data prior to "release"

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/Tepley-et-al-2017_Klamath#1]
@tepleya, I formatted the data you sent me and made a few tiny corrections (found a double decimal point, replaced "unknown" with UNK code for a few species). Once you approve, I will do a "release" that will archive the data in [Zenodo](https://zenodo.org/), where it will be assigned a DOI.

**Comment by teixeirak** [comment]
Also, feel free to edit anything -- repository name, README, repository settings, etc. You have admin permissions on this repository.

**Comment by tepleya** [comment]
I just checked the data files and everything looks good to me.
